# Dashboard Configuration
# This file contains configuration settings for the Streamlit dashboard
# It is typically generated by the streamlit_launcher.py script

import os

# Define the project root directory (typically TEST directory)
PROJECT_ROOT = os.path.abspath(os.path.dirname(os.path.dirname(__file__)))

# Define paths for data and models
DATA_DIR = os.path.join(PROJECT_ROOT, 'data')
MODELS_DIR = os.path.join(os.path.dirname(PROJECT_ROOT), 'models')

# Dashboard settings
DASHBOARD_TITLE = "Gun Retail Sales Dashboard"
DASHBOARD_ICON = "📊"
DASHBOARD_LAYOUT = "wide"
SIDEBAR_STATE = "expanded"

# Chart and visualization settings
DEFAULT_CHART_HEIGHT = 400
DEFAULT_CHART_WIDTH = 800
COLOR_PALETTE = {
    'primary': 'tab:blue',
    'secondary': 'tab:red',
    'tertiary': 'tab:green',
    'background': '#f0f2f6',
    'grid': '#ddd'
}

# Date range default settings
DEFAULT_LOOKBACK_DAYS = 90
DEFAULT_FORECAST_DAYS = 30

# Dashboard tabs
TABS = [
    "Historical Sales",
    "Forecast",
    "Category Comparison",
    "Feature Importance",
    "What-If Analysis"
]
